name: "Arguments Parsing"
description: "An action to parse input parameters and perform tasks like Fibonacci calculations."

inputs:
  enable_fib:
    description: "Enable Fibonacci calculation"
    required: true
    default: "true"
  max_threshold:
    description: "Maximum threshold for Fibonacci calculation"
    required: true
    default: "1000"
  github_token:
    description: "GitHub Token for Authentication"
    required: true
    default: ""
  pr_number:
    description: "Pull Request Number"
    required: true
    default: "1"
  owner:
    description: "GitHub Repository Owner"
    required: true
    default: ""
  repository:
    description: "GitHub Repository Name"
    required: true
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }}
    - ${{ inputs.repository}}
    - ${{ inputs.pr_number }}
    - ${{ inputs.github_token }}
    - ${{ inputs.owner}}
