
name: "Arguments Parsing"
description: "An action to parse input parameter"
inputs:
  enable_feature: 
    description: 'Enable fibonacci'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum threshold'
    required: true
    default: '500'
runs:
  using: 'composite'
  steps:
    - name: Run Argument parsing action
      run: |
        cargo run -- --enable-fib ${{ inputs.enable_fib}} --max-threshold ${{ inputs.max_threshold}}
      shell: bash
      
  
