
name: "Arguments Parsing"
description: "An action to parse input parameter"
inputs:
  enable_fib: 
    description: 'Enable fibonacci'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum threshold'
    required: true
    default: '1000'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.enable_fib}}
    - ${{ inputs.max_threshold}}
      
  
