# .github/workflows/test-action.yml
name: Test Hello World Rust Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello World Rust Action
        uses: ./
        
