name: Hello World Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello_world_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Uses hello_world_image
      uses: ./.github/workflows/hello_world_image 

    
