# .github/workflows/test-action.yml
name: Test Hello World Rust Action, Test input parsing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
  contents: read
          

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello World Rust Action && Argument Parsing Action
        uses: ./
        with:
          enable_fib: 'true'
          max_threshold: '1000'
          pr_number: ${{ github.event.pull_request.number}}
          github_token: ${{secrets.GITHUB_TOKEN}}
          owner: ${{github.owner}}
          repository: ${{github.repository}}
        
        
